project:
  type: book
  output-dir: docs

book:
  title: "R Essentials: A Beginnerâ€™s Guide to Data Analysis"
  author: "Tengku Muhammad Hanis Bin Tengku Mokhtar, PhD"
  date: today
  date-format: "MMM D, YYYY"
  cover-image: images/book_cover.png
  favicon: images/thumbnail2.png
  chapters:
    - index.qmd
    - about.qmd
    - what-is-R.qmd
    - install-r.qmd
    - use-rstudio.qmd
    - basic-r.qmd
    - data-wrangling.qmd
    - descriptive-stat.qmd
    - plotting.qmd
    - efficient-coding.qmd
    - data-explore.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

